config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  # get '/meals', to: 'meals#index'
  # get '/meals/:id', to: 'meals#show'
  # get '/meals/:new', to: 'meals#new'
  # get "index", to: "meals#index"
  # get "meals/:id", to: "meals#show"
  # get "meals/new", to: "meals#new"
  # post "meals", to: "meals#create"
  resources :orders, only: [:show]
  resources :meals do
    member do
    resources :orders, only: [:index, :new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user, dependent: :destroy
  has_many :orders, dependent: :destroy
  # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, presence: :true
  validates :description, presence: :true
  validates :price, presence: :true
  validates :date, presence: :true
  validates :stock, presence: :true
  #validates :photo presence true
  #validates :calorie presence true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :quantity, presence: :true






end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :meals, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates :name, presence: :true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
    # @order = Order.new
    # @user = User.all
  end

  def new
    @meal = Meal.new
  end

  def edit
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    if @meal.save
      redirect_to meal_path(@meal)
    else
      render :new
    end
  end

  def update
    if @meal.update(meal_params)
      redirect_to @meal, notice: 'Meal was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @meal.destroy
    redirect_to meals_url, notice: 'Meal was successfully destroyed.'
  end



      private

    def set_meal
      @meal = Meal.find(params[:id])
    end

    def meal_params
      params.require(:meal).permit(:description, :date, :name, :calories, :price, :photo, :photo_cache, :stock)
    end

end







  # def top
  #   @meals = Meal.where(stars: 5)
  # end
  # def chef
  # end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  #   @order = Reservation.all
    @orders = Order.all
  #   current_user.
  #   meals = Meal.all
  end

  def show
    # @meal = Meal.new
    # @order = Order.find(params[:id])
  end

  def new
    # @meal = Meal.find(params[:meal_id])
    @order = Order.new
  end

  def edit
  end


  def create
    @user = current_user
    @meal = Meal.find(params[:id])
    @order = Order.new(orders_params)
    @order.user = @user
    @order.meal = @meal
    # @order.user = User.all.sample


    if @order.save
      redirect_to order_path(@order)
    else
      render :new
      # redirect_to meal_path(Meal.find(params[:id])), alert: "La réservation a échoué"
    end

  end


  # def update
  #     if @order.update(order_params)
  #       redirect_to @order, notice: 'Order was successfully updated.'
  #     else
  #       render :edit
  #     end
  # end


  # def destroy
  #   @order.destroy
  #     redirect_to orders_url, notice: 'Orders was successfully destroyed.'
  # end

  private
    # def set_order
    #   @order = Order.find(params[:id])
    # end

    def orders_params
      params.require(:order).permit(:quantity)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>

  <%= render "shared/navbar" %>

  <div class="fill-navbar">

    &nbsp;
  </div>
    <%= render "shared/flashes" %>
  <div class="container">
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/meals/index.html.erb
<h1> Les plats </h1>

  <div class="container">
    <div class="row">
      <% @meals.each do |meal| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card">
            <%= cl_image_tag(meal.photo,
              width: 350, height: 350, crop: :fill) %>
            <div class="card-body">
              <h5 class="card-title"><%= meal.name %></h5>
              <p class="card-text"> <%= meal.description %> </p>
              <%= link_to "Description", meal_path(meal), :class => "btn btn-primary pipoup"%>
              <br>
            </div>
            <br>
          </div>
        </div>
      <%end%>
    </div>
  </div>

app/views/meals/new.html.erb
<h1>Add a new meal</h1>

<div class="container">
  <div class="all-edit">
    <%= simple_form_for(@meal) do |f| %>
      <div class="form-inputs">
        <div class="input-edit">
          <%= f.input :name %>
        </div>
        <div class="input-edit">
          <%= f.input :stock %>
        </div>
        <div class="input-edit">
          <%= f.input :description %>
        </div>
        <div class="input-edit">
          <%= f.input :calories %>
        </div>
        <div class="input-edit">
          <%= f.input :price %>
        </div>
        <div class="input-edit">
          <%= f.input :date %>
        </div>
        <div class="input-edit">
          <%= f.input :photo %>
        </div>
        <div class="input-edit">
          <%= f.input :photo_cache, as: :hidden %>
        </div>
      </div>
      <div class="form-actions">
        <div class= "submit-edit">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/meals/show.html.erb
  <div class="row">
    <h1><%=@meal.name%></h1>
  </div>
  <div class="row">
    <div class="col-xs-6">
    <h5> Les caractéristiques du plat sont : </h5>
    <ul>
      <li> Nom du plat : <%= @meal.name %></li>
      <li> Description : <%= @meal.description%></li>
      <li> Prix : <%= @meal.price %> euros </li>
      <li> Stock : <%= @meal.stock%> disponibles </li>
    </ul>

<%= link_to "Create an order", new_order_path, class: "btn btn-primary btn-lg my-btn" %>

<%= link_to "Return", meals_path, class: "btn btn-primary btn-lg my-btn" %>

    </div>
  </div>

app/views/orders/_form.html.erb
<%= simple_form_for [@order] do |f| %>
<%= f.input :quantity %>
<%= f.button :submit %>
 <% end %>

app/views/orders/index.html.erb
<h1>Votre commande a bien été enregistrée</h1>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Show Order</h1> -->

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> Your order has been created ! 🙈🍻 </td>

    </tr>
  </tbody>
</table>

<br>

app/views/pages/home.html.erb
<h1><%= "Elsa is back in the game" %></h1>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">

    <div class="item active">
      <%= image_tag("sj_passedat.jpg") %>
      <div class="carousel-caption">
        <h3>les saint-jacques de Gérald Passedat</h3>
        <p>***</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag("schrimp-rice.jpg") %>
      <div class="carousel-caption">
        <h3>Riz aux crevettes d'Alexandre Mazzia</h3>
        <p>**</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag("truite.jpg") %>
      <div class="carousel-caption">
        <h3>La truite fumée de Lionel Levy</h3>
        <p>*</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag("saumon.jpg") %>
      <div class="carousel-caption">
        <h3>le saumon mi-cuit de Gérald Passedat</h3>
        <p>***</p>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("lesetoiles.png", alt: "logo"), '/' %>
    <%= link_to " ", '#', id: "prov" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Tous les plats", meals_path %></li>
        <li><%= link_to "Se connecter", new_user_session_path %></li>
        <li><%= link_to "Se deconnecter", destroy_user_session_path, method: :delete %></li>
      </ul>
    </nav>
  </div>
</header>